const nichePage = (slug, name, audience, topics, review, market = 'global') => ({
  slug,
  title: `${name} Guest Posting Service | Relevant Editorial Links`,
  description: `Earn relevant ${name.toLowerCase()} backlinks through manual publisher research, original content and transparent placement checks for ${audience}.`,
  eyebrow: `${name} link building`,
  heading: `${name} Guest Posts Built for Relevance, Not Just Metrics`,
  intro: `Reach readers who already care about ${topics[0].toLowerCase()}, ${topics[1].toLowerCase()} and ${topics[2].toLowerCase()}. We research real publications, match each pitch to the site’s audience and share placement details before content moves forward.`,
  audience,
  topics,
  review,
  market,
  deliverables: [
    `A prospect list filtered for ${name.toLowerCase()} relevance`,
    'Original article written for the publisher’s readers',
    'Natural anchor and destination-page recommendation',
    'Live URL, placement details and post-publication check',
  ],
});

const servicePage = (slug, title, keyword, audience, outcome, differentiator) => ({
  slug,
  title,
  description: `${keyword} with manual research, clear quality checks and transparent reporting. Built for ${audience}.`,
  eyebrow: keyword,
  heading: `${keyword} That Supports Sustainable Organic Growth`,
  intro: `${outcome} Every campaign starts with the pages you need to grow, the audience you need to reach and the risks you want to avoid—not a preselected list of sites.`,
  audience,
  topics: ['Campaign planning', 'Publisher qualification', 'Editorial content'],
  review: differentiator,
  market: 'global',
  deliverables: [
    'Campaign brief and destination-page mapping',
    'Publisher research with relevance and traffic review',
    'Original editorial content and contextual link placement',
    'Live-link report with quality-control notes',
  ],
});

export const landingPages = [
  nichePage('travel-guest-post', 'Travel', 'tour operators, hotels, destination brands and travel SaaS teams', ['Destination guides', 'Hospitality trends', 'Responsible tourism'], 'We check destination fit, seasonal relevance and whether travel traffic comes from useful informational queries.'),
  nichePage('uk-guest-post', 'UK', 'brands that need visibility with audiences in the United Kingdom', ['UK business', 'Consumer advice', 'Local market trends'], 'We review UK traffic share, British English editorial standards and genuine local readership.', 'United Kingdom'),
  nichePage('web-design-guest-post', 'Web Design', 'design studios, developers, hosting brands and UX platforms', ['UX research', 'Frontend performance', 'Conversion-focused design'], 'We favour publications with practitioner audiences, visible authors and technically accurate editorial review.'),
  nichePage('canada-guest-post', 'Canada', 'companies targeting Canadian consumers and business buyers', ['Canadian business', 'Regional consumer guides', 'Technology adoption'], 'We validate Canadian search visibility, regional fit and locally useful editorial context.', 'Canada'),
  nichePage('uae-guest-post', 'UAE', 'brands reaching buyers in Dubai, Abu Dhabi and the wider Emirates', ['UAE business', 'Property and tourism', 'Regional technology'], 'We check UAE audience signals, regional relevance and English or Arabic market alignment.', 'United Arab Emirates'),
  nichePage('education-guest-post', 'Education', 'schools, universities, edtech products and training providers', ['Learning technology', 'Student outcomes', 'Professional development'], 'We avoid unsupported outcome claims and prioritise publications trusted by educators, learners or parents.'),
  nichePage('law-guest-post', 'Legal', 'law firms, legal software providers and compliance consultancies', ['Legal technology', 'Compliance education', 'Practice management'], 'Legal content requires careful sourcing, jurisdiction clarity and publishers that distinguish information from legal advice.'),
  nichePage('entrepreneur-guest-post', 'Entrepreneur', 'founders, startup advisors, accelerators and B2B providers', ['Startup operations', 'Founder finance', 'Market validation'], 'We look for active founder readership and practical editorial standards instead of broad motivational blogs.'),
  nichePage('tech-guest-post', 'Technology', 'software companies, IT providers and product-led startups', ['Software engineering', 'Digital transformation', 'Product strategy'], 'We verify topical depth, organic technology traffic and whether contributors demonstrate real subject knowledge.'),
  nichePage('cybersecurity-guest-post', 'Cybersecurity', 'security vendors, consultants and B2B technology teams', ['Threat prevention', 'Identity and access', 'Security compliance'], 'Claims must be technically defensible; we prioritise security-focused audiences and reject recycled breach-news sites.'),
  nichePage('cryptocurrency-guest-post', 'Cryptocurrency', 'blockchain products, exchanges, analytics platforms and Web3 teams', ['Blockchain infrastructure', 'Digital asset security', 'Crypto regulation'], 'We screen for transparent ownership, real readership and responsible financial language in a volatile, high-risk niche.'),
  nichePage('guest-post-australia', 'Australia', 'businesses seeking Australian customers and local search visibility', ['Australian business', 'Consumer services', 'Regional innovation'], 'We validate Australian traffic, local language conventions and editorial relevance to the intended state or national market.', 'Australia'),
  nichePage('real-estate-guest-post', 'Real Estate', 'agents, property platforms, developers and proptech brands', ['Home buying', 'Property investment', 'Market technology'], 'We distinguish local consumer publications from generic property blogs and require careful treatment of financial claims.'),
  nichePage('beauty-guest-post', 'Beauty', 'skincare, cosmetics, salon and personal-care brands', ['Skincare education', 'Beauty routines', 'Product formulation'], 'We assess audience fit, disclosure practices and whether health or product claims are handled responsibly.'),
  nichePage('fitness-write-for-us-guest-post', 'Fitness', 'gyms, coaches, sports products and wellness platforms', ['Training principles', 'Recovery', 'Sustainable habits'], 'We prioritise evidence-aware editorial policies and avoid sites promoting unsafe or unrealistic health outcomes.'),
  nichePage('fashion-guest-post', 'Fashion', 'apparel labels, retailers, designers and fashion technology brands', ['Sustainable fashion', 'Style guidance', 'Retail innovation'], 'We review visual and editorial quality, audience engagement and alignment with the brand’s price point and category.'),
  nichePage('finance-guest-post', 'Finance', 'fintech companies, advisers, accounting firms and financial publishers', ['Personal finance', 'Fintech products', 'Business accounting'], 'Finance is a trust-sensitive niche, so we check authorship, disclosures, source quality and misleading-claim risk.'),
  nichePage('home-improvement-guest-post', 'Home Improvement', 'contractors, home-service platforms and renovation brands', ['Renovation planning', 'Energy efficiency', 'Home maintenance'], 'We target practical homeowner audiences and publishers with clear project expertise rather than thin décor galleries.'),
  nichePage('gadgets-guest-post', 'Gadgets', 'consumer electronics brands, accessory makers and technology retailers', ['Product comparisons', 'Smart-home devices', 'Mobile accessories'], 'We review real product coverage, commercial transparency and search traffic beyond one-off launch news.'),
  nichePage('guest-post-spain', 'Spain', 'brands targeting customers and companies in Spain', ['Spanish business', 'Travel and lifestyle', 'Digital commerce'], 'We assess Spanish audience fit, language quality and whether regional context matches the campaign.', 'Spain'),
  nichePage('food-guest-post', 'Food', 'food brands, restaurants, kitchen products and hospitality businesses', ['Cooking techniques', 'Food culture', 'Restaurant operations'], 'We check recipe or culinary expertise, audience engagement and careful handling of nutrition or allergy claims.'),
  nichePage('automotive-guest-post', 'Automotive', 'dealers, parts brands, mobility startups and vehicle services', ['Vehicle ownership', 'EV technology', 'Maintenance guidance'], 'We favour publications with hands-on automotive expertise, stable buyer traffic and accurate safety information.'),
  nichePage('google-news-guest-post', 'Google News', 'brands seeking timely editorial coverage on established news publishers', ['Industry commentary', 'Company research', 'Data-led stories'], 'Inclusion is never promised: we verify current publication signals, editorial fit and newsworthiness before outreach.'),
  nichePage('wordpress-guest-post', 'WordPress', 'plugin developers, agencies, hosts and site owners', ['WordPress performance', 'Plugin workflows', 'Site security'], 'We seek technically credible WordPress publications and content that solves a specific administrator or developer problem.'),
  nichePage('ecommerce-guest-post', 'Ecommerce', 'online retailers, commerce platforms and conversion tools', ['Store optimisation', 'Customer retention', 'Commerce operations'], 'We qualify publishers by merchant readership, useful commercial queries and depth beyond generic dropshipping content.'),
  nichePage('german-guest-post', 'German', 'companies entering Germany or strengthening German-language visibility', ['German business', 'B2B technology', 'Consumer guidance'], 'We review native-language quality, German search traffic and market-specific editorial expectations.', 'Germany'),
  nichePage('wedding-guest-post', 'Wedding', 'venues, planners, photographers and wedding product brands', ['Wedding planning', 'Vendor selection', 'Budget and style'], 'We match publishers to planning stage, geography and service category so referral visibility is commercially useful.'),
  nichePage('lifestyle-guest-post', 'Lifestyle', 'consumer brands serving clearly defined interest-based audiences', ['Everyday wellbeing', 'Home and relationships', 'Personal development'], 'Lifestyle is broad, so we require a close audience match and reject sites whose categories have no editorial focus.'),
  nichePage('cbd-guest-post', 'CBD', 'compliant CBD brands, education platforms and wellness retailers', ['CBD education', 'Product quality', 'Responsible use'], 'We consider publisher policy, local advertising rules and health-claim risk; placement availability varies by jurisdiction.'),
  nichePage('marketing-guest-post', 'Marketing', 'agencies, martech companies and in-house growth teams', ['Content strategy', 'Demand generation', 'Marketing analytics'], 'We prioritise practitioner readership, original examples and organic visibility for real marketing problems.'),
  nichePage('business-guest-post', 'Business', 'B2B companies, professional services and growing organisations', ['Business operations', 'Leadership systems', 'Revenue strategy'], 'We narrow broad business inventory by buyer role, company stage and the topic of the destination page.'),
  nichePage('sports-guest-post', 'Sports', 'sports brands, clubs, training products and fan platforms', ['Performance analysis', 'Sports culture', 'Equipment guidance'], 'We qualify publishers by sport, audience location and whether coverage is original rather than scraped scores or news.'),
  nichePage('health-guest-post', 'Health', 'health platforms, clinics and wellness companies with review-ready content', ['Preventive health', 'Patient education', 'Healthcare technology'], 'Health content needs strong sourcing, qualified review where appropriate and no exaggerated medical outcomes.'),
  servicePage('guest-post-link-building', 'Guest Post Link Building Service | Manual Outreach', 'Guest post link building', 'SEO teams that need relevant editorial links at a controlled pace', 'Build links to strategically selected pages with anchors considered across the whole campaign.', 'We evaluate topical overlap, organic traffic patterns, outbound-link behaviour and editorial quality before approval.'),
  servicePage('high-da-guest-post-sites', 'High DA Guest Post Sites | Quality Beyond a Single Metric', 'High-authority guest post placements', 'brands that want authority without relying on DA alone', 'Use authority metrics as one screening signal while prioritising relevance, real traffic and editorial trust.', 'Every shortlist includes context beyond DA so a high score never hides weak traffic or irrelevant content.'),
  servicePage('seo-services', 'SEO Services for Sustainable Organic Growth', 'Practical SEO services', 'businesses that need technical, content and authority work aligned', 'Turn search demand into a prioritised roadmap covering crawlability, useful pages and credible off-page signals.', 'Recommendations are tied to measurable search problems, implementation effort and commercial relevance.'),
  servicePage('guest-posting-service', 'Guest Posting Service | Vetted Publishers and Original Content', 'Managed guest posting service', 'brands and agencies that want placements managed end to end', 'Move from target-page planning to publisher research, content approval and live-link reporting through one workflow.', 'Clients review placement options while we handle research, outreach, writing and publication follow-up.'),
  servicePage('guest-post-cost', 'Guest Post Cost and Pricing Guide | What Determines Value', 'Transparent guest post pricing', 'buyers comparing placements, retainers and quality levels', 'Understand what changes cost before buying: publisher demand, niche, traffic quality, editorial work and campaign volume.', 'We separate publisher fees, content requirements and management scope so quotes can be compared on equal terms.'),
  servicePage('saas-guest-posting-service', 'SaaS Guest Posting Service | Editorial Links for Software Brands', 'SaaS guest posting service', 'B2B SaaS, product-led growth and enterprise software teams', 'Build relevant mentions around use cases, integrations and problems your software helps solve.', 'Publisher matching considers ICP, funnel stage, topical adjacency and whether the article can earn qualified referral attention.'),
  servicePage('premium-guest-post', 'Premium Guest Posts | Selective Editorial Placements', 'Premium guest post placements', 'brands prioritising selectivity, editorial quality and stronger publications', 'Focus budget on fewer, better-matched opportunities with deeper publisher due diligence and custom content.', 'Premium means stricter qualification and editorial effort—not an unsupported promise about rankings or traffic.'),
  servicePage('guest-posting-agency', 'Guest Posting Agency | Strategy, Outreach and Reporting', 'Guest posting agency', 'in-house marketers and SEO agencies needing scalable delivery', 'Coordinate planning, prospecting, writing, approvals and reporting without losing control of quality.', 'Our workflow keeps placement decisions visible and avoids anonymous inventory or undisclosed substitutions.'),
  servicePage('white-label-guest-posting', 'White Label Guest Posting for SEO Agencies', 'White label guest posting', 'agencies delivering campaigns under their own client relationships', 'Add fulfilment capacity with client-ready reporting, defined approval stages and no supplier branding.', 'We protect agency relationships, follow campaign-level instructions and keep deliverables easy to hand off.'),
];

export const landingPageMap = Object.fromEntries(landingPages.map((page) => [page.slug, page]));
