import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, CheckCircle2 } from 'lucide-react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { Button } from '@/components/ui/button';
import PageSeo from '@/components/PageSeo';

const CaseStudyPage = () => (
  <>
    <PageSeo
      title="Guest Posting Case Study | Campaign Method and Reporting"
      description="See how a relevance-led guest posting campaign is planned, quality-checked and measured without inflated SEO promises."
      path="/case-study"
    />
    <Header />
    <main>
      <section className="bg-gradient-to-br from-slate-950 via-blue-950 to-slate-900 text-white py-20 lg:py-28"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><p className="text-blue-300 font-semibold uppercase tracking-wide mb-4">Campaign case study</p><h1 className="text-4xl md:text-6xl font-bold leading-tight mb-6">How Relevance-Led Outreach Turns Placements Into Useful SEO Assets</h1><p className="text-xl text-slate-300 max-w-3xl leading-relaxed">A transparent example of campaign planning, publisher qualification and measurement. Client-identifying data and invented performance claims are intentionally excluded.</p></div></section>
      <section className="py-16"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><p className="text-lg text-slate-700 leading-relaxed mb-10">The example begins with a common constraint: the client needs relevant third-party coverage, but a large generic site list would make approval difficult and could waste budget. The campaign therefore treats every placement as an editorial decision. The target page must already answer its intended query, the publisher must reach a related audience, and the proposed article must stand on its own even if the link is ignored.</p><div className="grid md:grid-cols-3 gap-6">{[['Challenge','A B2B software team had strong product pages but few editorial references from publications read by its buyers.'],['Strategy','Map links to useful resources, segment prospects by audience and publish at a measured pace with varied, natural anchors.'],['Measurement','Track live-link quality, destination-page impressions, relevant rankings and assisted conversions instead of reporting DA alone.']].map(([title,text])=><article key={title} className="border border-slate-200 rounded-2xl p-7"><h2 className="text-xl font-bold text-slate-900 mb-3">{title}</h2><p className="text-slate-600 leading-relaxed">{text}</p></article>)}</div></div></section>
      <section className="py-16 bg-slate-50 border-y border-slate-200"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-bold text-slate-900 mb-8">The campaign workflow</h2><div className="space-y-6">{['Audit destination pages and remove targets that do not yet satisfy search intent.','Build topic clusters around buyer problems rather than forcing exact-match commercial anchors.','Reject publishers with irrelevant traffic, unstable visibility or excessive unrelated sponsored content.','Write each article for the publication’s audience and document the reason for the contextual link.','Review live URLs and compare search visibility over an appropriate period without attributing every change to links.'].map(item=><div key={item} className="flex gap-3"><CheckCircle2 className="w-6 h-6 text-blue-600 shrink-0"/><p className="text-slate-700 leading-relaxed">{item}</p></div>)}</div></div></section>
      <section className="py-16"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-bold text-slate-900 mb-5">What a credible report should show</h2><p className="text-lg text-slate-600 leading-relaxed mb-7">A case study is only useful when the measurement has limits. Rankings can change because of content updates, technical fixes, competitors and search-system changes. We report placement facts separately from business outcomes and avoid presenting correlation as guaranteed causation.</p><Link to="/contact"><Button size="lg">Discuss your campaign <ArrowRight className="ml-2 w-5 h-5" /></Button></Link></div></section>
      <section className="py-16 bg-slate-50"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-bold text-slate-900 mb-5">Measurement framework and limitations</h2><p className="text-slate-700 leading-relaxed mb-5">Before outreach begins, the campaign records baseline impressions, clicks, priority-query positions and conversions for each destination page. Every approved publisher is logged with its topic, audience fit, traffic pattern, proposed article, anchor rationale, link attribute and live URL. This creates an audit trail that distinguishes completed work from an assumed SEO outcome.</p><p className="text-slate-700 leading-relaxed mb-5">Reviews use sensible comparison periods because new pages and links can take time to be crawled. Branded and non-branded queries are separated, and large content or technical changes are noted. A lift that appears after publication is treated as supporting evidence, not proof that one link caused the change.</p><p className="text-slate-700 leading-relaxed">This illustrative case study does not publish a client name, fabricated percentages or guaranteed rankings. Actual results depend on the starting site, competition, content quality, technical health and publisher decisions. The useful takeaway is the documented process: improve weak target pages first, prioritize relevance, reject questionable inventory and report what can be verified.</p></div></section>
    </main>
    <Footer />
  </>
);

export default CaseStudyPage;
